import { useState } from 'react'
import { AlertTriangle, Check, LockKeyhole, Pencil, RefreshCcw, Settings2, UserPlus, Users, X } from 'lucide-react'
import type { Gender, Participant, PlayerStat } from '../types'
import { generateBalancedRounds, type DoublesType } from '../lib/generator'

type Api = ReturnType<typeof import('../hooks/useAppData').useAppData>
export default function Admin({api,stats}:{api:Api;stats:PlayerStat[]}){
  const [pin,setPin]=useState(''); const [token,setToken]=useState(''); const [msg,setMsg]=useState(''); const [newName,setNewName]=useState(''); const [newPhoneLast4,setNewPhoneLast4]=useState(''); const [drawing,setDrawing]=useState(false); const [resetting,setResetting]=useState(false)
  const [newGender,setNewGender]=useState<Gender>('unspecified'); const [doublesType,setDoublesType]=useState<DoublesType>('open')
  const [roundCount,setRoundCount]=useState(4); const [court,setCourt]=useState(1); const [players,setPlayers]=useState<string[]>(['','','',''])
  const votes=api.data.fashionVotes.length, eligible=api.data.participants.filter(p=>p.is_active).length
  const login=async()=>{try{if(await api.verifyAdmin(pin)){setToken(pin);setMsg('관리자 모드가 열렸습니다.')}else setMsg('PIN이 올바르지 않습니다.')}catch(e){setMsg(message(e))}}
  const run=async(action:string,payload:Record<string,unknown>={})=>{try{await api.admin(action,payload,token);setMsg('저장했습니다.')}catch(e){setMsg(message(e))}}
  const draw=async()=>{const pool=stats.filter(s=>s.completed>0);if(!pool.length)return setMsg('완료 경기에 참여한 선수가 없습니다.');if(!confirm('럭키드로우 당첨자를 추첨할까요? 결과가 저장됩니다.'))return;setDrawing(true);setTimeout(async()=>{await run('lucky_draw',{pool_type:'played',exclude_award_winners:false});setDrawing(false);setMsg('🎉 추첨이 완료되었습니다. 이벤트 화면에서 당첨자를 확인하세요!')},1800)}
  const resetAll=async()=>{if(!confirm('참가자를 제외한 모든 행사 기록을 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;setResetting(true);setMsg('삭제 중입니다…');try{await api.resetEventData(token);setMsg('참가자를 제외한 모든 행사 기록을 삭제했습니다.')}catch(e){setMsg(`초기화 실패: ${message(e)}`)}finally{setResetting(false)}}
  const generate=()=>{const active=api.data.participants.filter(p=>p.is_active);const eligible=doublesType==='male'||doublesType==='female'?active.filter(p=>p.gender===doublesType):active;if(doublesType==='mixed'){const men=active.filter(p=>p.gender==='male').length,women=active.filter(p=>p.gender==='female').length;if(men<2||women<2)return setMsg('혼합복식은 남성 2명과 여성 2명 이상이 필요합니다.')}else if(eligible.length<4)return setMsg('선택한 복식 유형의 활성 참가자가 4명 이상 필요합니다.');if(!confirm(`기존 대기 경기를 바꾸고 ${roundCount}개 라운드를 자동 생성할까요?`))return;const first=Math.max(0,...api.data.matches.map(m=>m.match_number))+1;const base=Math.max(0,...api.data.rounds.filter(r=>api.data.matches.some(m=>m.round_id===r.id&&m.status!=='waiting')).map(r=>r.round_number));const result=generateBalancedRounds(api.data.participants,roundCount,first,doublesType);void run('generate_schedule',{rounds:result.map(r=>({roundNumber:r.roundNumber+base,rests:r.rests.map(p=>p.id),matches:r.matches.map(m=>({court:m.court,matchNumber:m.matchNumber,teamA:m.teamA.map(p=>p.id),teamB:m.teamB.map(p=>p.id)}))}))})}
  const createMatch=()=>{if(new Set(players).size!==4||players.some(x=>!x))return setMsg('서로 다른 선수 4명을 선택해주세요.');const next=Math.max(0,...api.data.matches.map(m=>m.match_number))+1;void run('create_match',{match_number:next,court_number:court,round_id:'',order_index:next,players})}
  if(!token)return <section className="page-section admin-login"><LockKeyhole/><p className="eyebrow">ADMIN ONLY</p><h2>관리자 PIN</h2><p>대진, 참가자, 경기 상태와 이벤트를 관리합니다.</p><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN 입력"/><button className="primary" onClick={login}>관리자 모드 열기</button>{msg&&<p>{msg}</p>}<small>데모 모드 기본 PIN: 1121</small></section>
  return <section className="page-section"><div className="section-title"><div><p className="eyebrow">CONTROL ROOM</p><h2>운영 관리</h2></div><button className="ghost" onClick={()=>setToken('')}>잠금</button></div>{msg&&<div className="admin-message">{msg}</div>}
    <div className="admin-grid">
      <AdminPanel icon={<Users/>} title="참가자 관리"><form className="participant-add-form" onSubmit={e=>{e.preventDefault();if(newName.trim()&&/^\d{4}$/.test(newPhoneLast4)){void run('add_participant',{name:newName.trim(),gender:newGender,phone_last4:newPhoneLast4});setNewName('');setNewPhoneLast4('')}}}><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="참가자 이름"/><input type="password" inputMode="numeric" value={newPhoneLast4} onChange={e=>setNewPhoneLast4(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="휴대폰 뒷자리 4개"/><GenderSelect value={newGender} onChange={setNewGender}/><button className="primary" disabled={!newName.trim()||newPhoneLast4.length!==4}><UserPlus size={18}/>추가</button></form><div className="gender-legend"><span>남 {api.data.participants.filter(p=>p.is_active&&p.gender==='male').length}</span><span>여 {api.data.participants.filter(p=>p.is_active&&p.gender==='female').length}</span><span>미지정 {api.data.participants.filter(p=>p.is_active&&p.gender==='unspecified').length}</span></div><div className="people-admin">{api.data.participants.map(p=><ParticipantAdminRow key={p.id} participant={p} onRun={run}/>)}</div></AdminPanel>
      <AdminPanel icon={<Settings2/>} title="패션왕 투표"><div className="metric-row"><div><b>{votes}</b><span>투표</span></div><div><b>{eligible-votes}</b><span>미투표</span></div><div><b>{eligible?Math.round(votes/eligible*100):0}%</b><span>투표율</span></div></div><div className="button-row"><button onClick={()=>run('vote_status',{status:'open'})}>투표 시작</button><button onClick={()=>run('vote_status',{status:'closed'})}>투표 마감</button></div><label className="switch-row"><span>투표 중 결과 공개</span><input type="checkbox" checked={api.data.settings.reveal_fashion_during_vote} onChange={e=>run('setting',{key:'reveal_fashion_during_vote',value:e.target.checked})}/></label></AdminPanel>
      <AdminPanel icon={<RefreshCcw/>} title="럭키드로우"><p>기본 대상: 실제 완료 경기 1회 이상 참여자</p><button className="primary full" disabled={drawing} onClick={draw}>{drawing?'두근두근… 🎾':'🎁 추첨하기'}</button></AdminPanel>
      <AdminPanel icon={<AlertTriangle/>} title="데이터 관리"><label>위로상 이름<input value={api.data.settings.resilience_award_name} onChange={e=>run('setting',{key:'resilience_award_name',value:e.target.value})}/></label><label className="switch-row"><span>중복 수상 허용</span><input type="checkbox" checked={api.data.settings.allow_duplicate_awards} onChange={e=>run('setting',{key:'allow_duplicate_awards',value:e.target.checked})}/></label><p>참가자와 로그인 정보는 유지하고 경기·라운드·점수 기록·투표·추첨 결과를 모두 삭제합니다.</p><button type="button" className="danger full" disabled={resetting} onClick={()=>void resetAll()}>{resetting?'삭제 중…':'참가자 외 모든 기록 삭제'}</button></AdminPanel>
      <AdminPanel icon={<Settings2/>} title="대진 자동 생성"><label>복식 유형<select value={doublesType} onChange={e=>setDoublesType(e.target.value as DoublesType)}><option value="open">자유 복식</option><option value="mixed">혼합복식</option><option value="male">남자복식</option><option value="female">여자복식</option></select></label><div className="inline-form"><input type="number" min="1" max="20" value={roundCount} onChange={e=>setRoundCount(Number(e.target.value))}/><button type="button" className="primary" onClick={generate}>균형 대진 생성</button></div><p>혼복은 팀마다 남성 1명·여성 1명으로 구성합니다. 경기 수와 휴식 편차도 함께 고려합니다.</p></AdminPanel>
      <AdminPanel icon={<Settings2/>} title="경기 수동 추가"><label>코트<select value={court} onChange={e=>setCourt(Number(e.target.value))}><option value="1">1코트</option><option value="2">2코트</option><option value="3">3코트</option></select></label><div className="player-selects">{players.map((value,i)=><select key={i} value={value} onChange={e=>setPlayers(x=>x.map((v,j)=>j===i?e.target.value:v))}><option value="">{i<2?'팀 A':'팀 B'} 선수 {i%2+1}</option>{api.data.participants.filter(p=>p.is_active).map(p=><option value={p.id} key={p.id}>{p.name} ({genderLabel(p.gender)})</option>)}</select>)}</div><button className="primary full" onClick={createMatch}>대기 경기 추가</button></AdminPanel>
    </div>
    <AdminPanel icon={<Settings2/>} title="경기 상태 및 점수"><div className="match-admin">{api.data.matches.map(m=><div key={m.id}><span><b>#{m.match_number}</b> {m.court_number}코트 · {m.team_a.map(p=>p.name).join('+')} vs {m.team_b.map(p=>p.name).join('+')}</span><em>{m.team_a_score}:{m.team_b_score}</em><select value={m.status} onChange={e=>api.setStatus(m.id,e.target.value as typeof m.status,token)}><option value="waiting">대기</option><option value="playing">진행중</option><option value="finished">종료</option><option value="cancelled">취소</option></select></div>)}</div></AdminPanel>
  </section>
}
function AdminPanel({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="admin-panel"><header>{icon}<h3>{title}</h3></header>{children}</article>}
function ParticipantAdminRow({participant,onRun}:{participant:Participant;onRun:(action:string,payload?:Record<string,unknown>)=>Promise<void>}){
  const [editing,setEditing]=useState(false); const [name,setName]=useState(participant.name); const [gender,setGender]=useState<Gender>(participant.gender); const [phoneLast4,setPhoneLast4]=useState('')
  const cancel=()=>{setName(participant.name);setGender(participant.gender);setPhoneLast4('');setEditing(false)}
  const save=async()=>{const clean=name.trim();if(!clean||phoneLast4.length!==0&&phoneLast4.length!==4)return;await onRun('update_participant',{id:participant.id,name:clean,gender,...(phoneLast4?{phone_last4:phoneLast4}:{})});setPhoneLast4('');setEditing(false)}
  return <div className={`participant-admin-row ${participant.is_active?'':'inactive'} ${editing?'editing':''}`}>{editing?<><input autoFocus value={name} maxLength={30} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void save();if(e.key==='Escape')cancel()}}/><input type="password" inputMode="numeric" value={phoneLast4} maxLength={4} onChange={e=>setPhoneLast4(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="새 뒷자리 (선택)"/><GenderSelect value={gender} onChange={setGender}/><button className="icon-action save" title="저장" onClick={save}><Check size={15}/></button><button className="icon-action" title="취소" onClick={cancel}><X size={15}/></button></>:<><span>{participant.name}<small>{genderLabel(participant.gender)}</small></span><button className="icon-action" title="이름·성별·휴대폰 뒷자리 수정" onClick={()=>setEditing(true)}><Pencil size={14}/></button><button className="active-toggle" onClick={()=>onRun('toggle_participant',{id:participant.id})}>{participant.is_active?'활성':'비활성'}</button></>}</div>
}
function GenderSelect({value,onChange}:{value:Gender;onChange:(gender:Gender)=>void}){return <select className="gender-select" aria-label="성별" value={value} onChange={e=>onChange(e.target.value as Gender)}><option value="male">남성</option><option value="female">여성</option><option value="unspecified">미지정</option></select>}
const genderLabel=(gender:Gender)=>gender==='male'?'남':gender==='female'?'여':'미지정'
const message=(e:unknown)=>e instanceof Error?e.message:'요청을 처리하지 못했습니다.'
